spring:
  flyway:
    enabled: true
  application:
    name: restaurant
  jwt:
     secret: ${JWT_SECRET}
     accessTokenExpiration: 7200000 # 2 Hours
     refreshTokenExpiration: 604800
  profiles:
    active: dev
