spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_api?createDatabaseIfNotExist=true
    username: root
    password: goodmorning
  jpa:
    show-sql: true
  jwt:
     secret: ${JWT_SECRET}
     accessTokenExpiration: 3000 # 5 minutes
     refreshTokenExpiration: 604800 # 7 days