spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_api?createDatabaseIfNotExist=true
    username: root
    password: goodmorning
  jpa:
    show-sql: true
app:
  websiteUrl: http://localhost:4242