spring:
  flyway:
    enabled: true
  application:
    name: restaurant
  jwt:
     secret: ${JWT_SECRET}
     accessTokenExpiration: 7200 # 2 Hours
     refreshTokenExpiration: 604800 # 2 Weeks
  profiles:
    active: dev
